gazebo_ros_control:
    pid_gains:
      shoulder_pan_joint: {p: 10, i: 0, d: 1}
      shoulder_lift_joint: {p: 10, i: 0, d: 1}
      elbow_joint: {p: 10, i: 0, d: 1}
      wrist_1_joint: {p: 10, i: 0, d: 1.0}
      wrist_2_joint: {p: 10, i: 0, d: 1.0}
      wrist_3_joint: {p: 10, i: 0, d: 1.0}