
position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.1
    shoulder_pan_joint: {trajectory: 0.1, goal: 0.2}
    shoulder_lift_joint: {trajectory: 0.1, goal: 0.2}
    elbow_joint: {trajectory: 0.1, goal: 0.2}
    wrist_1_joint: {trajectory: 0.1, goal: 0.2}
    wrist_2_joint: {trajectory: 0.1, goal: 0.2}
    wrist_3_joint: {trajectory: 0.1, goal: 0.2}

  stop_trajectory_duration: 0.5
  state_publish_rate:  50
  action_monitor_rate: 30
  
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
controller_list:
    - name: position_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint