sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: camera1/depth_registered/points
    max_range: 1.0
    # max_range: 4.0
    point_subsample: 1
    # padding_offset: 0.1
    padding_offset: 0.05
    padding_scale: 1.0
    max_update_rate: 10.0
    # filtered_cloud_topic: filtered_cloud
